# Numpy
Bu bölümde, beyzbol dünyasına dalacağız. Yol boyunca, veri bilimi yapmak için güçlü bir paket olan numpy'nin temellerini öğreneceksiniz.

Python betiğinde, bazı beyzbol oyuncularının santimetre cinsinden yüksekliğini temsil eden bir beyzbol listesi zaten tanımlanmıştır. Bundan bir numpy dizisi oluşturmak için buraya ve oraya biraz kod ekleyebilir misiniz?

In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


Beyzbol oyuncularının boyu

Sen büyük bir beyzbol hayranısın. MLB'yi (Major League Baseball) aramaya ve ana oyuncuların boyları hakkında daha fazla istatistik istemeye karar verdiniz. Normal bir Python listesi olarak saklanan binden fazla oyuncu hakkında veri iletirler: height_in. Yükseklik inç cinsinden ifade edilir. Bundan numpy bir dizi yapabilir ve birimleri metreye çevirebilir misiniz?

height_in zaten mevcut ve numpy paketi yüklendi, böylece hemen başlayabilirsiniz

In [3]:
# height_in is available as a regular list

# Import numpy
import numpy as np

height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74]
# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_in_m = np_height_in*0.0254
print(np_height_in_m)

# Print np_height_m


[74 74 72 72 73 69 69 71 76 71 73 73 74 74 69 70 73 75 78 79 76 74]
[1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796]


Beyzbol oyuncusunun BMI'si

MLB ayrıca ağırlık verilerini analiz etmenize izin verir. Yine, her ikisi de normal Python listeleri olarak mevcuttur: height_in ve Weight_lb. Height_in inç cinsindendir ve Weight_lb pound cinsindendir.

Artık her beyzbol oyuncusunun BMI'sini hesaplamak mümkün. Height_in'i doğru birimlerle numpy dizisine dönüştürmek için Python kodu çalışma alanında zaten mevcut. Adım adım talimatları izleyin ve oyunu bitirin!

In [6]:
# height_in and weight_lb are available as regular lists

# Import numpy
import numpy as np
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230]
# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb)*0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg/np_height_m**2
print(bmi)

# Print out bmi


[23.11037639 27.60406069 28.48080465 28.48080465 24.80333518 25.99036864
 30.86356276 27.89402921 28.11789135 25.10462629 24.80333518 23.7478741
 23.75233129 20.54255679 26.58105883 26.54444207 24.93526781 23.12315842
 25.30771077 25.91025019 24.95310704 29.52992539]


Hafif beyzbol oyuncuları

Hem normal Python listelerini hem de sayısal dizileri alt kümelemek için köşeli parantezleri kullanabilirsiniz:

x = [4 , 9 , 6, 3, 1]

x[1]

import numpy as np

y = np.array(x)

y[1]
Özellikle numpy için, boolean numpy dizilerini de kullanabilirsiniz:

high = y > 5

y[high]

Tüm beyzbol oyuncularının BMI'sini hesaplayan kod zaten dahil edilmiştir. Talimatları takip edin ve verilerden ilginç şeyler ortaya çıkarın!

In [7]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi<21
# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])


[False False False False False False False False False False False False
 False  True False False False False False False False False]
[20.54255679]


### NumPy Yan Etkileri

Her şeyden önce, numpy dizileri farklı türlerde öğeler içeremez. Böyle bir liste oluşturmaya çalışırsanız, bazı öğelerin türleri, homojen bir liste ile sonuçlanacak şekilde değiştirilir. Bu tip zorlama olarak bilinir.

İkincisi, +, -, * ve / gibi tipik aritmetik operatörler, normal Python listeleri ve numpy dizileri için farklı bir anlama sahiptir.

Bu kod satırına bir göz atın:

np.array([True, 1, 2]) + np.array([3, 4, False])

Tam olarak aynı Python nesnesini hangi kod parçasının oluşturduğunu söyleyebilir misiniz? Numpy paketi zaten np olarak içe aktarılmıştır, bu nedenle IPython Shell'de hemen denemeye başlayabilirsiniz!

In [1]:
np.array([True, 1, 2]) + np.array([3, 4, False])
# [4,5,2]

NameError: name 'np' is not defined

### NumPy Dizilerini Alt Kümeleme

Bunu kendi gözlerinizle gördünüz: Python listeleri ve numpy dizileri bazen farklı davranır. Neyse ki, bu dünyada hala kesinlikler var. Örneğin, alt kümeleme (listelerde veya dizilerde köşeli parantez kullanarak) tamamen aynı şekilde çalışır. Bunu kendiniz görmek için IPython Shell'de aşağıdaki kod satırlarını deneyin:

x = ["a", "b", "c"]

x[1]

np_x = np.array(x)

np_x[1]

Düzenleyicideki komut dosyası zaten numpy'yi np olarak içe aktaran ve MLB oynatıcılarının hem yüksekliğini hem de ağırlığını numpy dizileri olarak saklayan kodu içerir.

In [10]:
# height_in and weight_lb are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 20
print(np_weight_lb[20])

# Print out sub-array of np_height_in: index 10 up to and including index 14
print(np_height_in[10:14])

205
[73 73 74 74]


### İlk 2D NumPy Diziniz

Gerçek MLB verileri üzerinde çalışmadan önce, küçük bir liste listesinden bir 2B numpy dizisi oluşturmaya çalışalım.

Bu alıştırmada, beyzbol bir liste listesidir. Ana liste 4 öğe içerir. Bu öğelerin her biri, bu sırayla 4 beyzbol oyuncusunun boy ve ağırlığını içeren bir listedir. beyzbol senaryoda zaten sizin için kodlanmış.

In [11]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

print(np_baseball.shape)

# Print out the shape of np_baseball


<class 'numpy.ndarray'>
(4, 2)


2D formda beyzbol verileri

MLB verilerine bir kez daha bakın ve tüm bu bilgileri bir 2B numpy dizisinde yeniden yapılandırmanın daha mantıklı olduğunu anlayın. Bu dizide, hakkında bilgi sahibi olduğunuz 1015 beyzbol oyuncusuna karşılık gelen 1015 satır ve 2 sütun (boy ve kilo için) olmalıdır.

MLB yine çok yardımcı oldu ve verileri size farklı bir yapıda, bir Python listeleri listesinde iletti. Bu liste listesinde, her bir alt liste, tek bir beyzbol oyuncusunun boyunu ve ağırlığını temsil eder. Bu gömülü listenin adı beyzbol.

Numpy'nin ekstra işlevselliğinin kilidini açmak için verileri 2B dizi olarak saklayabilir misiniz?

In [12]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


### 2D NumPy Dizilerini Alt Kümeleme

2D numpy diziniz düzenli bir yapıya sahipse, yani her satır ve sütun sabit sayıda değere sahipse, karmaşık alt kümeleme yöntemleri çok kolay hale gelir. "a" ve "c" öğelerinin bir liste listesinden çıkarıldığı aşağıdaki koda bir göz atın.

düzenli liste listesi
x = [["a", "b"], ["c", "d"]]

[x[0][0], x[1][0]]

dizi

import numpy as np

np_x = np.array(x)

np_x[:,0]

Normal Python listeleri için bu gerçek bir acıdır. Ancak 2D numpy dizileri için oldukça sezgiseldir! Virgülden önceki dizinler satırları, virgülden sonraki dizinler sütunları gösterir. : dilimleme içindir; bu örnekte Python'a tüm satırları dahil etmesini söyler.

Önceden yüklenmiş beyzbol listesini 2B numpy dizisine dönüştüren kod zaten komut dosyasındadır. İlk sütun, oyuncuların boyunu inç cinsinden içerir ve ikinci sütun, oyuncu ağırlığını pound cinsinden tutar. Doğru seçimleri yapmak için birkaç satır ekleyin. Python'da ilk öğenin 0 dizininde olduğunu unutmayın!

In [14]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 2th row of np_baseball
print(np_baseball[2,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 4th player
print(np_baseball[3,0])


[210.   98.5]
188.0


2D Aritmetik

Tüm beyzbol oyuncuları için Vücut Kitle İndeksini nasıl hesapladığınızı hatırlıyor musunuz? numpy, tüm hesaplamaları eleman bazında (yani eleman eleman) gerçekleştirebildi. 2D numpy dizileri için bu farklı değil! Matrisleri tek sayılarla, vektörlerle ve diğer matrislerle birleştirebilirsiniz.

Aşağıdaki kodu IPython kabuğunda yürütün ve anlayıp anlamadığınızı görün:

In [15]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [22]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array

# Import numpy package
import numpy as np

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
# print(np_baseball+updated)

# Create numpy array: conversion
conversion = np.array([0.0254,0.453592])

# Print out product of np_baseball and conversion
print(np_baseball*conversion)

[[ 4.572     35.5616128]
 [ 5.461     46.5838984]
 [ 5.334     44.678812 ]
 [ 4.7752    34.1101184]]


# Ortalamaya karşı medyan

Artık verileriniz için daha iyi bir his elde etmek için numpy işlevlerini nasıl kullanacağınızı biliyorsunuz. Temel olarak, numpy'yi içe aktarmaya ve ardından numpy dizilerinde birkaç basit işlevi çağırmaya gelir:

import numpy as np

x = [1, 4, 8, 10, 12]

np.mean(x)

np.median(x)

Beyzbol verileri, 3 sütunlu (boy, kilo, yaş) ve 1015 satırlı bir 2D numpy dizisi olarak mevcuttur. Bu numpy dizisinin adı np_baseball'dur. Ancak verileri yeniden yapılandırdıktan sonra, bazı yükseklik değerlerinin anormal derecede yüksek olduğunu fark ediyorsunuz. Talimatları izleyin ve sözde aykırı değerlerle uğraşıyorsanız hangi özet istatistiğin en uygun olduğunu keşfedin.

In [23]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


Beyzbol verilerini keşfedin

Ortalama ve medyan birbirinden çok uzak olduğu için MLB'ye şikayet etmeye karar veriyorsunuz. Hatayı bulurlar ve düzeltilmiş verileri size gönderirler. Yine üç sütunlu bir 2D Numpy dizisi np_baseball olarak mevcuttur.

Editördeki Python betiği, farklı özet istatistiklerle bilgilendirici mesajları yazdırmak için zaten kod içerir. İşi bitirebilir misin?

In [24]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0],np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
